
-- PARAMETRIZACAO BASICA

Insert into ISSR_ONLINE.PARAM_ISSUER_PROCESSO (ID_ISSUER,NM_PROCESSO,NM_PARAMETRO,DS_PARAMETRO,VL_PARAMETRO_ALFA,VL_PARAMETRO_NUM) values 
('1004','LIMITADOR_EC','DT_HABILITACAO_REF','Monitorar ECs habilitados apos data','20210101',20200101);

Insert into ISSR_ONLINE.PARAM_ISSUER_PROCESSO (ID_ISSUER,NM_PROCESSO,NM_PARAMETRO,DS_PARAMETRO,VL_PARAMETRO_ALFA,VL_PARAMETRO_NUM) values 
('1004','LIMITADOR_EC','URL_WS_BLOCK_MERCHANT','PATH COMPLETO WS MANAGE MERCHANT','http://192.168.123.10:8081/CMS-STD-WEB-SERVICES-REST-ACQUIRER/cms/rest/api/merchants/sendBlockMerchant',null);

Insert into ISSR_ONLINE.PARAM_ISSUER_PROCESSO (ID_ISSUER,NM_PROCESSO,NM_PARAMETRO,DS_PARAMETRO,VL_PARAMETRO_ALFA,VL_PARAMETRO_NUM) values 
('1004','LIMITADOR_EC','ULT_ID_PROCESSADO','Ult ID v_trans_iso_issr_all processado',null,'9999999999');

Insert into ISSR_ONLINE.PARAM_ISSUER_PROCESSO (ID_ISSUER,NM_PROCESSO,NM_PARAMETRO,DS_PARAMETRO,VL_PARAMETRO_ALFA,VL_PARAMETRO_NUM) values 
('1004','LIMITADOR_EC','DE_PARA_PRODUTO_7_1','Parametrizacao produto e tarjeta','7_1','13');

Insert into ISSR_ONLINE.PARAM_ISSUER_PROCESSO (ID_ISSUER,NM_PROCESSO,NM_PARAMETRO,DS_PARAMETRO,VL_PARAMETRO_ALFA,VL_PARAMETRO_NUM) values 
('1004','LIMITADOR_EC','DE_PARA_PRODUTO_7_2','Parametrizacao produto e tarjeta','7_2','14');

Insert into ISSR_ONLINE.PARAM_ISSUER_PROCESSO (ID_ISSUER,NM_PROCESSO,NM_PARAMETRO,DS_PARAMETRO,VL_PARAMETRO_ALFA,VL_PARAMETRO_NUM) values 
('1004','LIMITADOR_EC','DE_PARA_PRODUTO_7_3','Parametrizacao produto e tarjeta','7_3','15');

Insert into ISSR_ONLINE.PARAM_ISSUER_PROCESSO (ID_ISSUER,NM_PROCESSO,NM_PARAMETRO,DS_PARAMETRO,VL_PARAMETRO_ALFA,VL_PARAMETRO_NUM) values 
('1004','LIMITADOR_EC','DE_PARA_PRODUTO_7_4','Parametrizacao produto e tarjeta','7_4','21');

Insert into ISSR_ONLINE.PARAM_ISSUER_PROCESSO (ID_ISSUER,NM_PROCESSO,NM_PARAMETRO,DS_PARAMETRO,VL_PARAMETRO_ALFA,VL_PARAMETRO_NUM) values 
('1004','LIMITADOR_EC','DE_PARA_PRODUTO_8_1','Parametrizacao produto e tarjeta','8_1','17');

Insert into ISSR_ONLINE.PARAM_ISSUER_PROCESSO (ID_ISSUER,NM_PROCESSO,NM_PARAMETRO,DS_PARAMETRO,VL_PARAMETRO_ALFA,VL_PARAMETRO_NUM) values 
('1004','LIMITADOR_EC','DE_PARA_PRODUTO_9_1','Parametrizacao produto e tarjeta','9_1','18');

Insert into ISSR_ONLINE.PARAM_ISSUER_PROCESSO (ID_ISSUER,NM_PROCESSO,NM_PARAMETRO,DS_PARAMETRO,VL_PARAMETRO_ALFA,VL_PARAMETRO_NUM) values ('1004','LIMITADOR_EC','GENERIC_QT_13','Qt max que um EC pode transacionar/dia','13','650');

Insert into ISSR_ONLINE.PARAM_ISSUER_PROCESSO (ID_ISSUER,NM_PROCESSO,NM_PARAMETRO,DS_PARAMETRO,VL_PARAMETRO_ALFA,VL_PARAMETRO_NUM) values ('1004','LIMITADOR_EC','GENERIC_QT_14','Qt max que um EC pode transacionar/dia','14','650');

Insert into ISSR_ONLINE.PARAM_ISSUER_PROCESSO (ID_ISSUER,NM_PROCESSO,NM_PARAMETRO,DS_PARAMETRO,VL_PARAMETRO_ALFA,VL_PARAMETRO_NUM) values ('1004','LIMITADOR_EC','GENERIC_QT_15','Qt max que um EC pode transacionar/dia','15','650');

Insert into ISSR_ONLINE.PARAM_ISSUER_PROCESSO (ID_ISSUER,NM_PROCESSO,NM_PARAMETRO,DS_PARAMETRO,VL_PARAMETRO_ALFA,VL_PARAMETRO_NUM) values ('1004','LIMITADOR_EC','GENERIC_QT_17','Qt max que um EC pode transacionar/dia','17','900');

Insert into ISSR_ONLINE.PARAM_ISSUER_PROCESSO (ID_ISSUER,NM_PROCESSO,NM_PARAMETRO,DS_PARAMETRO,VL_PARAMETRO_ALFA,VL_PARAMETRO_NUM) values ('1004','LIMITADOR_EC','GENERIC_QT_18','Qt max que um EC pode transacionar/dia','18','650');

Insert into ISSR_ONLINE.PARAM_ISSUER_PROCESSO (ID_ISSUER,NM_PROCESSO,NM_PARAMETRO,DS_PARAMETRO,VL_PARAMETRO_ALFA,VL_PARAMETRO_NUM) values ('1004','LIMITADOR_EC','GENERIC_QT_21','Qt max que um EC pode transacionar/dia','21','650');

Insert into ISSR_ONLINE.PARAM_ISSUER_PROCESSO (ID_ISSUER,NM_PROCESSO,NM_PARAMETRO,DS_PARAMETRO,VL_PARAMETRO_ALFA,VL_PARAMETRO_NUM) values ('1004','LIMITADOR_EC','GENERIC_VL_13','Vl max que um EC pode transacionar/dia','13','400000');

Insert into ISSR_ONLINE.PARAM_ISSUER_PROCESSO (ID_ISSUER,NM_PROCESSO,NM_PARAMETRO,DS_PARAMETRO,VL_PARAMETRO_ALFA,VL_PARAMETRO_NUM) values ('1004','LIMITADOR_EC','GENERIC_VL_14','Vl max que um EC pode transacionar/dia','14','400000');

Insert into ISSR_ONLINE.PARAM_ISSUER_PROCESSO (ID_ISSUER,NM_PROCESSO,NM_PARAMETRO,DS_PARAMETRO,VL_PARAMETRO_ALFA,VL_PARAMETRO_NUM) values ('1004','LIMITADOR_EC','GENERIC_VL_15','Vl max que um EC pode transacionar/dia','15','400000');

Insert into ISSR_ONLINE.PARAM_ISSUER_PROCESSO (ID_ISSUER,NM_PROCESSO,NM_PARAMETRO,DS_PARAMETRO,VL_PARAMETRO_ALFA,VL_PARAMETRO_NUM) values ('1004','LIMITADOR_EC','GENERIC_VL_17','Vl max que um EC pode transacionar/dia','17','150000');

Insert into ISSR_ONLINE.PARAM_ISSUER_PROCESSO (ID_ISSUER,NM_PROCESSO,NM_PARAMETRO,DS_PARAMETRO,VL_PARAMETRO_ALFA,VL_PARAMETRO_NUM) values ('1004','LIMITADOR_EC','GENERIC_VL_18','Vl max que um EC pode transacionar/dia','18','400000');

Insert into ISSR_ONLINE.PARAM_ISSUER_PROCESSO (ID_ISSUER,NM_PROCESSO,NM_PARAMETRO,DS_PARAMETRO,VL_PARAMETRO_ALFA,VL_PARAMETRO_NUM) values ('1004','LIMITADOR_EC','GENERIC_VL_21','Vl max que um EC pode transacionar/dia','21','400000');

Insert into ISSR_ONLINE.PARAM_ISSUER_PROCESSO (ID_ISSUER,NM_PROCESSO,NM_PARAMETRO,DS_PARAMETRO,VL_PARAMETRO_ALFA,VL_PARAMETRO_NUM) values ('1004','LIMITADOR_EC','DT_HABILITACAO_REF','Monitorar ECs habilitados apos data','20200101','20200101');


commit;
