--USE [FEPHP_H] HOMOLOGAÇÃO DESCOMENTAR

USE [FEPHP] 

INSERT INTO [FEPHP].[dbo].[STATUSTRANSACAO] VALUES ('B1', 'EC EXCEDEU LIMITE DIARIO');
--SELECT * FROM [FEPHP].[dbo].[STATUSTRANSACAO] where IDSTATUSTRANSACAO = 'B1';
                  
INSERT INTO [FEPHP].[dbo].[CODIGORETORNOPAYWARE] VALUES ('B1', 'B1');
--SELECT * FROM [FEPHP].[dbo].[CODIGORETORNOPAYWARE] where STATUS_TRANSACAO = 'B1';

                  
INSERT INTO [FEPHP].[dbo].[ACQUIRERDEPARASTATUSTRANSACAO] (ID_ACQUIRER, ID_AUTORIZADOR, IDSTATUSTRANSACAO, CODIGORESPOSTAREDE, MENSAGEM)
SELECT ID_ACQUIRER, ID_AUTORIZADOR, 'B1', CODIGORESPOSTAREDE, MENSAGEM FROM [FEPHP].[dbo].[ACQUIRERDEPARASTATUSTRANSACAO]
WHERE IDSTATUSTRANSACAO = 'M2';

--SELECT * FROM [FEPHP].[dbo].[ACQUIRERDEPARASTATUSTRANSACAO] where IDSTATUSTRANSACAO = 'B1';

GO